### ISSUE TITLE
License

### ISSUE THREAD

**Issue by therealjumbo** [bitbank2/gif_play#2]
Can you add a LICENSE or COPYING file? It isn't clear from this:
```
//
// GIF Play
//
// Project started 6/19/2018
// Play animated GIF files directly onto a framebuffer or SPI LCD
// Written by Larry Bank
// bitbank@pobox.com
// Copyright (c) 2018 BitBank Software, Inc.
//
```
If this is free to use and/or modify or not.

**Comment by bitbank2** [comment]
Thanks for reminding me. This topic was brought up from another of my repos today. I've been considering various options and I think I'll set it as Apache 2.0.

**Comment by therealjumbo** [comment]
Awesome, thank you we would greatly appreciate it. I also have a few modifications I wanted to put in a PR, but I thought it might be best to know the license first...

**Comment by bitbank2** [comment]
Updated to Apache 2.0 license
